[versions]
minecraft = "1.21"

# Platform libraries

fabric_loader = "0.15.10"
fabric_api = "0.100.1+1.21"

forge = "1.20.4-49.0.30"

neoforge = "21.0.0-beta"

quilt_loader = "0.25.0"
quilt_standard_libraries = "8.0.0-alpha.12+1.20.4"

# Regular libraries

battery = "1.1.0"

# Modding libraries

modmenu = "11.0.0-beta.1"
cloth_config = "15.0.127"

mixinextras = "0.3.5"

architectury = "3.4.155"
architectury_loom = "1.6.397"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Platform libraries

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
# fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
qsl_lifecycle_events = { module = "org.quiltmc.qsl.core:lifecycle_events", version.ref = "quilt_standard_libraries" }

# Regular libraries

battery = { module = "net.lostluma:battery", version.ref = "battery" }

# Modding libraries

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
cloth_config = { module = "me.shedaniel.cloth:cloth-config", version.ref = "cloth_config" }

mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras_forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }

architectury_plugin = { module = "architectury-plugin:architectury-plugin.gradle.plugin", version.ref = "architectury" }
architectury_loom = { module = "dev.architectury.loom:dev.architectury.loom.gradle.plugin", version.ref = "architectury_loom" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }
architectury_loom = { id = "dev.architectury.loom", version.ref = "architectury_loom" }
