[versions]
minecraft = "1.19"

# Platform libraries

fabric_loader = "0.15.10"
fabric_api = "0.55.3+1.19"

forge = "1.19-41.1.0"

neoforge = "20.4.160-beta"

quilt_loader = "0.25.0"
quilt_standard_libraries = "2.0.0-beta.16+1.19"

# Third-party libraries

modmenu = "4.0.0"
cloth_config = "7.0.72"

mixinextras = "0.3.5"

[libraries]
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }

# Platform libraries

fabric_loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric_loader" }
# fabric_api = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric_api" }

forge = { module = "net.minecraftforge:forge", version.ref = "forge" }

neoforge = { module = "net.neoforged:neoforge", version.ref = "neoforge" }

quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
qsl_lifecycle_events = { module = "org.quiltmc.qsl.core:lifecycle_events", version.ref = "quilt_standard_libraries" }

# Third-party libraries

modmenu = { module = "com.terraformersmc:modmenu", version.ref = "modmenu" }
cloth_config = { module = "me.shedaniel.cloth:cloth-config", version.ref = "cloth_config" }

mixinextras_common = { module = "io.github.llamalad7:mixinextras-common", version.ref = "mixinextras" }
mixinextras_forge = { module = "io.github.llamalad7:mixinextras-forge", version.ref = "mixinextras" }

[bundles]

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version = "8.1.1" }

architectury = { id = "architectury-plugin", version = "3.4.155" }
architectury_loom = { id = "dev.architectury.loom", version = "1.6.394" }
