modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/juliand665/Dynamic-FPS/issues"

[[mods]]
modId = "dynamic_fps"
namespace = "net.lostluma"
version = "${version}"
displayName = "Dynamic FPS"
authors = "juliand665 & LostLuma"
description = "Reduce resource usage while Minecraft is in the background or idle."
logoFile = "dynamic_fps.png"
displayTest = "IGNORE_ALL_VERSION"
credits = """
Thanks to:
  Authors:
    juliand665
    LostLuma

  Contributors:
    altrisi
    DenaryDev
    dima-dencep
    EuropaYou
    parly
    Setadokalo
    Siphalor
    sisby-folk
    triphora

  Translators:
    AlphaKR93
    Altegar
    BurrConnie
    DecafDawren
    egeesin
    EuropaYou
    Felix14-v2
    FITFC
    GuNanOvO
    Hubry
    ImVietnam
    ishi-sama
    kyrtion
    LotuxPunk
    Madis0
    mpustovoi
    notlin4
    Pixaurora
    raspberrygitq
    Rhbarber
    RinixGG
    Samekichi
    Taarek
    TheBossMagnus
    TheLegendofSaram
    wicivo
    XfedeX
"""
modUrl = "https://dapprgames.com/mods"
displayURL = "https://dapprgames.com/mods"
updateJSONURL = "https://api.lostluma.net/updates/dynamic-fps?platform=neoforge&provider=modrinth"

[[mixins]]
config = "dynamic_fps.mixins.json"

[[mixins]]
config = "dynamic_fps-common.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.dynamic_fps]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.2,1.20.4]"
ordering = "NONE"
side = "CLIENT"

[[dependencies.dynamic_fps]]
modId = "cloth_config"
mandatory = true
versionRange = "[1,)"
ordering = "NONE"
side = "CLIENT"
