name: build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        java: [
          17,
          21,
        ]
        os: [
          ubuntu-22.04,
          windows-2022
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v2
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: setup gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-read-only: ${{ github.ref != 'refs/heads/main' }}
      - name: build
        run: ./gradlew build --warning-mode=all
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '21' }} # Upload artifacts from one job, ignore the rest
        uses: actions/upload-artifact@v4
        with:
          name: dynamic-fps-artifacts
          path: build/libs
          if-no-files-found: error
